/*
 * AVC firmware packet lockstep test — host-runnable, zero dependencies.
 *
 * Replays golden vectors generated by the Python side (services/ingest.py
 * build_packet) through avc_packet_build and requires byte-exact output.
 * Regeneration recipe (run from repo root):
 *
 *   python - <<EOF
 *   from services.ingest import build_packet
 *   pkt = build_packet(287454020, 48879, {"mic": [0.5, -0.25, 0.0],
 *        "piezo": [0.1, -0.1], "pressure": [0.5], "airflow": [-0.2]})
 *   print(pkt.hex())
 *   EOF
 *
 * Build + run on any C99 host compiler:
 *   gcc -std=c99 -Wall -Wextra -I../main -o test_packet test_packet.c ../main/packet.c
 *   ./test_packet
 */
#include <stdio.h>
#include <string.h>

#include "packet.h"

static int failures = 0;
static int checks = 0;

#define CHECK(cond, msg)                                                  \
    do {                                                                  \
        ++checks;                                                         \
        if (!(cond)) {                                                    \
            ++failures;                                                   \
            printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, (msg));        \
        }                                                                 \
    } while (0)

static int hex_nibble(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

/* Parse a hex string into out; returns byte count or -1 on bad input. */
static int hex_to_bytes(const char *hex, uint8_t *out, size_t cap)
{
    size_t n = strlen(hex);
    if (n % 2u != 0u) {
        return -1;
    }
    if (n / 2u > cap) {
        return -1;
    }
    for (size_t i = 0; i < n; i += 2u) {
        int hi = hex_nibble(hex[i]);
        int lo = hex_nibble(hex[i + 1]);
        if (hi < 0 || lo < 0) {
            return -1;
        }
        out[i / 2u] = (uint8_t)((hi << 4) | lo);
    }
    return (int)(n / 2u);
}

static void check_vector(const char *name,
                         uint32_t seq_no,
                         uint32_t timestamp_ms,
                         const avc_sensor_block_t *blocks,
                         uint8_t n_blocks,
                         const char *golden_hex)
{
    uint8_t golden[AVC_PACKET_MAX_LEN];
    uint8_t built[AVC_PACKET_MAX_LEN];
    int glen = hex_to_bytes(golden_hex, golden, sizeof(golden));
    if (glen < 0) {
        printf("FAIL %s: bad golden hex literal in test source\n", name);
        ++failures;
        return;
    }

    size_t blen = avc_packet_build(seq_no, timestamp_ms, blocks, n_blocks,
                                    built, sizeof(built));
    if (blen == 0u) {
        printf("FAIL %s: avc_packet_build returned 0\n", name);
        ++failures;
        return;
    }

    ++checks;
    if (blen != (size_t)glen || memcmp(built, golden, (size_t)glen) != 0) {
        ++failures;
        printf("FAIL %s: %zu bytes built vs %d golden\n", name, blen, glen);
        printf("  built : ");
        for (size_t i = 0; i < blen; ++i) printf("%02x", built[i]);
        printf("\n  golden: %s\n", golden_hex);
        return;
    }

    /* Footer CRC must also verify when recomputed standalone. */
    uint16_t crc_recv = (uint16_t)(built[blen - 2u] |
                                   ((uint16_t)built[blen - 1u] << 8));
    uint16_t crc_calc = avc_crc16(built, blen - AVC_PACKET_FOOTER_SIZE);
    CHECK(crc_recv == crc_calc, "embedded CRC does not match recomputed CRC");
    printf("PASS %s: %d bytes, CRC %#06x\n", name, glen, crc_recv);
}

int main(void)
{
    /* ---- CRC16 reference value (CCITT-FALSE check string) ---- */
    CHECK(avc_crc16((const uint8_t *)"123456789", 9) == 0x29B1u,
          "CRC16('123456789') != 0x29B1");

    /* ---- incremental CRC == one-shot CRC ---- */
    {
        const uint8_t data[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
        uint16_t whole = avc_crc16(data, sizeof(data));
        uint16_t split = avc_crc16_update(0xFFFFu, data, 5);
        split = avc_crc16_update(split, data + 5, 5);
        CHECK(whole == split, "incremental CRC != one-shot CRC");
    }

    /* ---- golden vector: all four sensors ----
     * seq 287454020 (0x11223344), ts 48879 (0x0000BEEF), mask 0x0F
     * mic [16384, -8192, 0], piezo [3277, -3277],
     * pressure [16384], airflow [-6553]  (pre-quantized int16) */
    {
        static const int16_t mic3[] = {16384, -8192, 0};
        static const int16_t piezo2[] = {3277, -3277};
        static const int16_t press1[] = {16384};
        static const int16_t air1[] = {-6553};
        const avc_sensor_block_t blocks[4] = {
            {AVC_SENSOR_MIC,      mic3,   3},
            {AVC_SENSOR_PIEZO,   piezo2, 2},
            {AVC_SENSOR_PRESSURE, press1, 1},
            {AVC_SENSOR_AIRFLOW, air1,   1},
        };
        check_vector("VEC_ALL", 287454020u, 48879u, blocks, 4,
            "44332211efbe00000f0300004000e000000200cd0c33f301000040010067e6182e");
    }

    /* ---- golden vector: mic only, negative samples, monotone ramp ----
     * seq 7, ts 123456, mask 0x01
     * mic [-32767, -23405, -14043, -4681, 4681, 14043, 23405, 32767] */
    {
        static const int16_t mic8[] = {-32767, -23405, -14043, -4681,
                                       4681, 14043, 23405, 32767};
        const avc_sensor_block_t blocks[1] = {
            {AVC_SENSOR_MIC, mic8, 8},
        };
        check_vector("VEC_MIC", 7u, 123456u, blocks, 1,
            "0700000040e20100010800018093a425c9b7ed4912db366d5bff7f0c0d");
    }

    /* ---- golden vector: piezo only, single max sample ----
     * seq 1, ts 1, mask 0x02, piezo [32767] */
    {
        static const int16_t piezo1[] = {32767};
        const avc_sensor_block_t blocks[1] = {
            {AVC_SENSOR_PIEZO, piezo1, 1},
        };
        check_vector("VEC_PIEZO", 1u, 1u, blocks, 1,
            "0100000001000000020100ff7ffc38");
    }

    /* ---- golden vector: empty mic block (count 0, no samples) ----
     * seq 42, ts 99, mask 0x01 — exercises the zero-count path */
    {
        const avc_sensor_block_t blocks[1] = {
            {AVC_SENSOR_MIC, NULL, 0},
        };
        check_vector("VEC_EMPTY", 42u, 99u, blocks, 1,
            "2a00000063000000010000e020");
    }

    /* ---- header constants pinned against the Python side ---- */
    CHECK(AVC_PACKET_HEADER_SIZE == 9u, "header size != 9");
    CHECK(AVC_PACKET_FOOTER_SIZE == 2u, "footer size != 2");
    CHECK(AVC_SENSOR_MIC == 0x01u && AVC_SENSOR_PIEZO == 0x02u &&
          AVC_SENSOR_PRESSURE == 0x04u && AVC_SENSOR_AIRFLOW == 0x08u,
          "sensor bit constants drifted from Python mask layout");

    /* ---- argument validation ---- */
    {
        static const int16_t one[] = {1};
        const avc_sensor_block_t ok_blocks[1] = {{AVC_SENSOR_MIC, one, 1}};
        uint8_t buf[AVC_PACKET_MAX_LEN];

        CHECK(avc_packet_build(1, 1, NULL, 1, buf, sizeof(buf)) == 0u,
              "NULL blocks accepted");
        CHECK(avc_packet_build(1, 1, ok_blocks, 1, NULL, sizeof(buf)) == 0u,
              "NULL out accepted");
        CHECK(avc_packet_build(1, 1, ok_blocks, 0, buf, sizeof(buf)) == 0u,
              "zero blocks accepted");

        /* not a single-bit flag */
        {
            const avc_sensor_block_t bad[1] = {{0x03u, one, 1}};
            CHECK(avc_packet_build(1, 1, bad, 1, buf, sizeof(buf)) == 0u,
                  "multi-bit sensor_bit accepted");
        }
        /* descending bit order */
        {
            const avc_sensor_block_t bad[2] = {
                {AVC_SENSOR_PIEZO, one, 1},
                {AVC_SENSOR_MIC, one, 1},
            };
            CHECK(avc_packet_build(1, 1, bad, 2, buf, sizeof(buf)) == 0u,
                  "descending block order accepted");
        }
        /* duplicate bit */
        {
            const avc_sensor_block_t bad[2] = {
                {AVC_SENSOR_MIC, one, 1},
                {AVC_SENSOR_MIC, one, 1},
            };
            CHECK(avc_packet_build(1, 1, bad, 2, buf, sizeof(buf)) == 0u,
                  "duplicate block bit accepted");
        }
        /* insufficient capacity: exact need for 1 sample is 9+2+2+2 = 15 */
        {
            uint8_t tiny[14];
            CHECK(avc_packet_build(1, 1, ok_blocks, 1, tiny, sizeof(tiny)) == 0u,
                  "undersized buffer accepted");
        }
        /* capacity exactly sufficient must succeed */
        {
            uint8_t exact[15];
            CHECK(avc_packet_build(1, 1, ok_blocks, 1, exact, sizeof(exact)) == 15u,
                  "exact-size buffer rejected");
        }
        /* NULL samples with nonzero count rejected */
        {
            const avc_sensor_block_t bad[1] = {{AVC_SENSOR_MIC, NULL, 1}};
            CHECK(avc_packet_build(1, 1, bad, 1, buf, sizeof(buf)) == 0u,
                  "NULL samples with count>0 accepted");
        }
        /* NULL samples with zero count: empty block is legal (count 0) */
        {
            const avc_sensor_block_t empty[1] = {{AVC_SENSOR_MIC, NULL, 0}};
            uint8_t out[16];
            CHECK(avc_packet_build(1, 1, empty, 1, out, sizeof(out)) ==
                  AVC_PACKET_HEADER_SIZE + 2u + AVC_PACKET_FOOTER_SIZE,
                  "empty block rejected");
        }
    }

    printf("%d checks, %d failures\n", checks, failures);
    if (failures != 0) {
        printf("TEST FAILED\n");
        return 1;
    }
    printf("ALL TESTS PASSED\n");
    return 0;
}
