/*
 * AVC packet wire format — C mirror of services/ingest.py (Python).
 *
 * PINNED LAYOUT (do not change one side without the other):
 *
 *   Header (9 bytes, little-endian):
 *     uint32 seq_no
 *     uint32 timestamp_ms
 *     uint8  sensor_mask      bit0=mic, bit1=piezo, bit2=pressure, bit3=airflow
 *
 *   Payload: for each enabled sensor in ascending bit order:
 *     uint16 sample_count
 *     int16  samples[sample_count]   (little-endian, pre-quantized)
 *
 *   Footer: uint16 CRC16-CCITT over header+payload (poly 0x1021, init 0xFFFF,
 *           no reflection, no final xor).
 *
 * Golden vectors for lockstep testing live in firmware/test/test_packet.c
 * and are generated by the Python side (services/ingest.py build_packet).
 */
#ifndef AVC_PACKET_H
#define AVC_PACKET_H

#include <stddef.h>
#include <stdint.h>

#define AVC_PACKET_HEADER_SIZE 9u
#define AVC_PACKET_FOOTER_SIZE 2u

/* sensor_mask bits — must equal the Python constants in services/ingest.py */
#define AVC_SENSOR_MIC      0x01u
#define AVC_SENSOR_PIEZO    0x02u
#define AVC_SENSOR_PRESSURE 0x04u
#define AVC_SENSOR_AIRFLOW  0x08u
#define AVC_SENSOR_ALL      0x0Fu

/* Nominal acquisition rates (TRD 4.1) and 500 ms window sample budgets. */
#define AVC_MIC_RATE_HZ        16000u
#define AVC_PIEZO_RATE_HZ       1000u
#define AVC_PRESSURE_RATE_HZ     100u
#define AVC_AIRFLOW_RATE_HZ      100u
#define AVC_WINDOW_MS            500u

#define AVC_MIC_WINDOW_MAX      8000u  /* 16 kHz * 0.5 s */
#define AVC_PIEZO_WINDOW_MAX     500u  /*  1 kHz * 0.5 s */
#define AVC_PRESSURE_WINDOW_MAX   50u  /* 100 Hz * 0.5 s */
#define AVC_AIRFLOW_WINDOW_MAX    50u  /* 100 Hz * 0.5 s */

/* Worst-case packet: header + 4 blocks + all samples + CRC. */
#define AVC_PACKET_MAX_LEN \
    (AVC_PACKET_HEADER_SIZE + \
     4u * 2u + \
     2u * (AVC_MIC_WINDOW_MAX + AVC_PIEZO_WINDOW_MAX + \
           AVC_PRESSURE_WINDOW_MAX + AVC_AIRFLOW_WINDOW_MAX) + \
     AVC_PACKET_FOOTER_SIZE)

/* One sensor's pre-quantized contribution to a packet. `sensor_bit` must be
 * exactly one of AVC_SENSOR_*; blocks are written in ascending bit order
 * (asserted by the builder: duplicate bits are rejected). */
typedef struct {
    uint8_t         sensor_bit;
    const int16_t  *samples;   /* little-endian int16, host order on ESP32 */
    uint16_t        count;
} avc_sensor_block_t;

/* CRC16-CCITT, poly 0x1021, init 0xFFFF — identical to services.ingest.crc16_ccitt. */
uint16_t avc_crc16(const uint8_t *data, size_t len);

/* Incremental variant (for streaming CRCs). */
uint16_t avc_crc16_update(uint16_t crc, const uint8_t *data, size_t len);

/* Serialize blocks into `out` (capacity `cap`). Returns total packet length,
 * or 0 if the buffer is too small / arguments are invalid. The mask is
 * computed from the block list; blocks must arrive in ascending bit order. */
size_t avc_packet_build(uint32_t seq_no,
                         uint32_t timestamp_ms,
                         const avc_sensor_block_t *blocks,
                         uint8_t n_blocks,
                         uint8_t *out,
                         size_t cap);

#endif /* AVC_PACKET_H */
